### ISSUE TITLE
State of API2 implementation and usage questions

### ISSUE THREAD

**Issue by castilma** [vineyardkoeln/churchtools-api#11]
I'm planing to build a website that uses the data we have on church.tools, but can be styled as we wish. So it will be like a reimplementation of the frontend of the mychurch.church.tools website. I'm still figuring out, whether I want to implement the connection to the backend via JS in the webbrowser or via php on my webserver. If I chose the latter, this project seems useful, but I have some questions.

1. Is this project still maintained? The last change was last year.
2. Are you actively using this project yourself, or have you switched to another solution?
3. How much of the API2 is implemented (percentagewise)?
4. Why are you using the Ajax APi to get the login token [here](https://github.com/vineyardkoeln/churchtools-api/blob/62e203f74f1e43df35b4bfbf794625a5ac565e9b/src/ChurchTools/Api2/RestApi2.php#L46)? Why not via the rest api as explained [here](https://intern.church.tools/wiki/30/API%20Authentication#LoginToken)?

5. How is the authentication supposed to work with this package?
the CT docs say one should always send a valid session cookie (as it is faster) and only if it expires, one should use the login token. when you use the login token, you get a new valid session cookie in the response. Are you using the session cookie? it seems, only the login token is stored in the RestApi2 Object. (sry, my php knowledge is very limited.)
6. What CT user should the webserver use? should we create a special CT user for the website? then we need to make permission checks on our site, and the webserver contains login data for an account with many( maybe all) rights on CT. Or should we better ask the user for his CT username and password and the webserver forwards them to CT? it feels wrong, to handle user names and passwords for another website. 
7. suppose we take the latter: how do we handle the session cookie and login token? is it ok to store one or both on the webserver for longer than just the current request? it would probably be better to store both on the client and then use the session-cookie (sent with every request). Only if we notice, that it expired, we ask the client for the login token, get and forward the new session-cookie and forget the the login token again. but the way RestApi2 is currently written, it looks like there is no way to create a client object with just a session cookie. can you tell me why?

I feel like some questions are beginner questions, but that's just what I am. Thanks for your understanding.

**Comment by YetiCGN** [comment]
Hi and thanks for your interest in this project!

1. and 2. I developed this package in 2018 in order to integrate ChurchTools with our website and Slack. It is currently still in use to remind people of open positions for a Sunday service via Slack. The need for this project arose from the complexity and non-RESTfulness of the V1 API. A lot of the problems from back then have been addressed by the V2 RESTful API, which is why I personally haven't spent much time on this recently. @a-schild has done some work for the V2 API to integrate it here, but in my opinion it would need a lot of streamlining work and refactoring to be of use. I think for PHP you're better off today if you just query their REST API directly. Although I don't have much experience with the V2 API myself, it looks better and well useable without the need for a wrapper project.

If you decide upon a frontend implementation, there's a great client project from the ChurchTools developers themselves: https://github.com/churchtools/churchtools-js-client

3. I couldn't say, but maybe André can shed some light on that?
4. Because back then it was [the only way](https://api.church.tools/class-CTLoginModule.html) to do it and nobody has bothered yet to change that.
5. Since the main use case at Vineyard Köln is in a daily cronjob, there was no need to persist any token between requests. You start the job, log in, do your thing, then the script ends and doesn't run again for the next 24 hours. If you are planning on integrating it into another application which pulls a lot of data in realtime, that part probably needs improvement.
6. We access ChurchTools via a single user with abundant permissions. You could do a user-based login and wouldn't need to ask the user for their password, just their [API login token](https://intern.church.tools/wiki/30/API%20Authentication#LoginToken).
7. Since this was never the intended use case, it's outside the scope of this project. I think you're better off implementing the API access yourself.

However, if you find that an API client project for PHP is still valuable, feel free to share your improvements as a pull request - or create your own GitHub project. 🙂 

Be blessed
Jörn

**Comment by a-schild** [comment]
@castilma 

1. In the last 6 months we have reevaluated what SW we use for our church, and we will continue for some parts with CT, but others will be migrated away to another solution in the next months.
For this project, I will provide a larger update in the next 1-2 months, but I won't put much effort in it in the long term.
But if you do a new start, perhaps look at this: https://github.com/5pm-HDH/churchtools-api

3. The REST api covers mainly Calendar, Persons and Groups along with some helpers like Tags.
The API2 gto stuck due to a very inconsistent openapi.json description provided by CT. It does basically define the entities which are used/provided.
But then on all GET/POST/PUT requests, they don't reference the defined entities, but redefine them over and over again.

This way, no automatic mapping/reusing php classes can be generated, and as I have just checked, it's still the same way :(
I did get in touch with some CT develppers about this, but apparently it's not on their list of priorities.

4. Some parts of CT are not yet REST capable, so you have to use the old api, and since that was already implemented ;)

For 5-6:
This is just the part we will move away from CT.
What's the benefit of having Events+Calendar in CT, but then not even beeing able to publish a picture/pdf and some additional metadata?
Here also, we have been in touch with CT to enhance+finance such a feature in CT, so that the web content of events could be put into CT, but there is currently no way they will do it.

If you wish to contribute to the project, of course you are welcome and I would also integrate you pull requests.
But perhaps the other library is better suited?
